#Pentagonal numbers are generated by the formula,
#P_n = n(3n−1)/2. The first ten pentagonal numbers are:
#
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
#It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8.
#However, their difference, 70 − 22 = 48, is not pentagonal.
#
#Find the pair of pentagonal numbers, P_j and P_k, for
#which their sum and difference are pentagonal and D =
#|Pk − Pj| is minimised; what is the value of D?

from utils import Utils

def p44():
    u = Utils()
    limit = 3000
    pl = [u.pentagonal(i) for i in xrange(limit)]
    for a in xrange(1, limit):
        for b in xrange(1, limit):
            if a > b:
                c = pl[a] + pl[b]
                d = pl[a] - pl[b]
                if u.chop(c, pl) > -1 and u.chop(d, pl) > -1:
                    print a, b, pl[a], pl[b],\
                        pl[pl.index(c)],\
                        pl.index(c),\
                        pl[pl.index(d)],\
                        pl.index(d)

import time
start = time.time()
p44()
print time.time() - start